"""Build the complete UR5e SAC vs PPO Colab notebook."""
import json

def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

def code(src):
    return {"cell_type": "code", "metadata": {}, "source": src, "execution_count": None, "outputs": []}

cells = []

# ====== CELL 0: Title ======
cells.append(md([
    "# \ud83e\udd16 UR5e Pick & Place \u2014 SAC vs PPO\n",
    "## Reinforcement Learning v\u1edbi PyBullet\n",
    "**Platform:** Google Colab Free T4 GPU | **Framework:** Stable-Baselines3 + Gymnasium\n",
    "\n",
    "---\n",
    "### M\u1ee5c l\u1ee5c\n",
    "1. Setup & Install\n",
    "2. Custom Gym Environment\n",
    "3. Sanity Check & Analysis\n",
    "4. Hyperparameter Tuning (Optuna)\n",
    "5. Train SAC \u2014 3 seeds\n",
    "6. Train PPO \u2014 3 seeds\n",
    "7. Evaluation & Statistical Analysis\n",
    "8. Learning Curves & Plots\n",
    "9. Video Demo\n",
    "10. Resume Training (n\u1ebfu disconnect)\n",
    "\n",
    "---\n",
    "> **Colab Free:** GPU T4 15GB | CPU 2 vCPU | RAM 12GB | `n_envs=2`\n",
    "\n",
    "> **Ref:** [leesweqq/ur5_reinforcement_learning_grasp_object](https://github.com/leesweqq/ur5_reinforcement_learning_grasp_object)"
]))

# ====== CELL 1: Setup ======
cells.append(md(["## 1. Setup & Install"]))
cells.append(code([
    "# [1.1] Mount Drive\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "import os\n",
    "\n",
    "BASE = '/content/drive/MyDrive/ur5e_rl'\n",
    "for d in [\n",
    "    f'{BASE}/models/sac', f'{BASE}/models/ppo', f'{BASE}/models/optuna',\n",
    "    f'{BASE}/logs/sac', f'{BASE}/logs/ppo', f'{BASE}/logs/tb',\n",
    "    f'{BASE}/norm', f'{BASE}/videos', f'{BASE}/results',\n",
    "]:\n",
    "    os.makedirs(d, exist_ok=True)\n",
    "print('\u2705 Drive mounted & folders ready')\n",
    "\n",
    "# [1.2] Install\n",
    "!pip install -q stable-baselines3[extra] pybullet gymnasium optuna tensorboard imageio imageio-ffmpeg scipy\n",
    "print('\u2705 Packages installed')\n",
    "\n",
    "# [1.3] Clone repo\n",
    "REPO_URL = 'https://github.com/Elsa9999/Do_An_RoBot_V2.git'  # <-- THAY URL REPO CUA BAN\n",
    "PROJECT  = '/content/ur5e_project'\n",
    "if not os.path.exists(PROJECT):\n",
    "    !git clone {REPO_URL} {PROJECT}\n",
    "%cd {PROJECT}\n",
    "\n",
    "# [1.4] Path\n",
    "import sys\n",
    "sys.path.insert(0, PROJECT)\n",
    "\n",
    "from kinematics.forward_kinematics import forward_kinematics\n",
    "from kinematics.inverse_kinematics import inverse_kinematics\n",
    "from kinematics.workspace_validator import WorkspaceValidator\n",
    "from simulation.environment import UR5eEnvironment\n",
    "from utils.transforms import local_to_world, world_to_local\n",
    "print('\u2705 Project imports OK')\n",
    "\n",
    "# [1.5] GPU + CPU\n",
    "import torch, multiprocessing, numpy as np, random\n",
    "assert torch.cuda.is_available(), '\u274c No GPU!'\n",
    "print(f'\u2705 GPU: {torch.cuda.get_device_name(0)}')\n",
    "print(f'\u2705 VRAM: {torch.cuda.get_device_properties(0).total_mem/1e9:.1f}GB')\n",
    "\n",
    "N_CPU  = multiprocessing.cpu_count()\n",
    "N_ENVS = min(2, N_CPU)\n",
    "print(f'\u2705 CPU: {N_CPU} cores -> n_envs={N_ENVS}')\n",
    "\n",
    "SEEDS = [42, 123, 777]\n",
    "random.seed(42); np.random.seed(42); torch.manual_seed(42)\n",
    "print(f'\u2705 Seeds: {SEEDS}')"
]))

# ====== CELL 2: Env ======
cells.append(md(["## 2. Custom Gym Environment"]))
cells.append(code([
    "import gymnasium as gym\n",
    "import numpy as np\n",
    "import pybullet as p\n",
    "from gymnasium import spaces\n",
    "from scipy.spatial.transform import Rotation\n",
    "\n",
    "class UR5eGymEnv(gym.Env):\n",
    "    metadata = {'render_modes': ['rgb_array']}\n",
    "    MAX_STEPS, PICK_THRESHOLD, ACTION_SCALE = 200, 0.05, 0.03\n",
    "    HOME_POSE = [0, -1.5708, 1.5708, -1.5708, -1.5708, 0]\n",
    "    CURRICULUM = [{'name':'easy','after':0},{'name':'medium','after':50000},{'name':'hard','after':150000}]\n",
    "\n",
    "    def __init__(self, gui=False, curriculum=True):\n",
    "        super().__init__()\n",
    "        import os\n",
    "        self._env = UR5eEnvironment(gui=gui and 'COLAB_GPU' not in os.environ)\n",
    "        self._validator = WorkspaceValidator()\n",
    "        self._curriculum = curriculum\n",
    "        self._global_steps = self._curriculum_stage = self._steps = 0\n",
    "        self._prev_dist = None\n",
    "        self._prev_action = np.zeros(3)\n",
    "        self._q_current = list(self.HOME_POSE)\n",
    "        self._dq_current = [0.0]*6\n",
    "        self._picked = False\n",
    "        # Obs 25D: q(6)+dq(6)+ee_pos(3)+ee_quat(4)+obj_pos(3)+rel(3)\n",
    "        self.observation_space = spaces.Box(-10.0, 10.0, (25,), np.float32)\n",
    "        self.action_space = spaces.Box(-1.0, 1.0, (3,), np.float32)\n",
    "\n",
    "    def _get_obs(self):\n",
    "        q = np.array(self._q_current, dtype=np.float32)\n",
    "        dq = np.array(self._dq_current, dtype=np.float32)\n",
    "        fk = forward_kinematics(self._q_current)\n",
    "        ee_w = np.array(local_to_world(fk['position']), dtype=np.float32)\n",
    "        ee_quat = Rotation.from_euler('zyx',[fk['euler'][2],fk['euler'][1],fk['euler'][0]]).as_quat().astype(np.float32)\n",
    "        obj = np.array(self._env.get_object_pose()[0], dtype=np.float32)\n",
    "        return np.concatenate([q, dq, ee_w, ee_quat, obj, obj-ee_w])\n",
    "\n",
    "    def _compute_reward(self, action):\n",
    "        fk = forward_kinematics(self._q_current)\n",
    "        ee_w = np.array(local_to_world(fk['position']))\n",
    "        obj = np.array(self._env.get_object_pose()[0])\n",
    "        dist = float(np.linalg.norm(ee_w - obj))\n",
    "        r = -dist*2.0 + (self._prev_dist-dist)*5.0 - 0.1\n",
    "        r -= float(np.linalg.norm(action-self._prev_action))*0.05\n",
    "        r -= float(np.linalg.norm(action))*0.1\n",
    "        self._prev_dist = dist\n",
    "        if dist < self.PICK_THRESHOLD:\n",
    "            r += 50.0; self._picked = True\n",
    "        ok, _ = self._validator.is_valid_ee(ee_w.tolist())\n",
    "        if not ok: r -= 2.0\n",
    "        return float(np.clip(r, -10.0, 55.0))\n",
    "\n",
    "    def reset(self, seed=None, options=None):\n",
    "        super().reset(seed=seed)\n",
    "        if self._curriculum:\n",
    "            for i,s in enumerate(self.CURRICULUM):\n",
    "                if self._global_steps >= s['after']: self._curriculum_stage = i\n",
    "        self._steps = 0; self._picked = False\n",
    "        self._prev_action = np.zeros(3)\n",
    "        self._q_current = list(self.HOME_POSE); self._dq_current = [0.0]*6\n",
    "        self._env.reset()\n",
    "        obs = self._get_obs()\n",
    "        self._prev_dist = float(np.linalg.norm(obs[18:21]))\n",
    "        return obs, {'stage': self.CURRICULUM[self._curriculum_stage]['name']}\n",
    "\n",
    "    def step(self, action):\n",
    "        self._steps += 1; self._global_steps += 1\n",
    "        dx,dy,dz = np.clip(action,-1,1) * self.ACTION_SCALE\n",
    "        fk = forward_kinematics(self._q_current)\n",
    "        ee_w = local_to_world(fk['position'])\n",
    "        w_new = [ee_w[0]+dx, ee_w[1]+dy, ee_w[2]+dz]\n",
    "        safe = self._validator.clamp_to_workspace(w_new)\n",
    "        l_new = world_to_local(safe)\n",
    "        ik = inverse_kinematics(l_new, list(fk['euler']), q_current=self._q_current)\n",
    "        ik_ok = False\n",
    "        if ik['best'] is not None:\n",
    "            q_new = ik['best']\n",
    "            self._dq_current = [(q_new[i]-self._q_current[i])*60 for i in range(6)]\n",
    "            self._q_current = q_new\n",
    "            self._env.set_joint_positions(self._q_current); ik_ok = True\n",
    "        else:\n",
    "            self._dq_current = [0.0]*6\n",
    "        self._env.step(5)\n",
    "        reward = self._compute_reward(action)\n",
    "        if not ik_ok: reward = float(np.clip(reward-2.0, -10.0, 55.0))\n",
    "        self._prev_action = action.copy()\n",
    "        return (self._get_obs(), reward, self._picked, self._steps>=self.MAX_STEPS,\n",
    "                {'picked':self._picked,'ik_success':ik_ok,'stage':self.CURRICULUM[self._curriculum_stage]['name']})\n",
    "\n",
    "    def render(self): return None\n",
    "    def close(self): self._env.close()\n",
    "\n",
    "# Verify\n",
    "from stable_baselines3.common.env_checker import check_env\n",
    "_t = UR5eGymEnv(); check_env(_t, warn=True); _t.close()\n",
    "print('\u2705 Environment check passed!')"
]))

# ====== CELL 3: Sanity ======
cells.append(md(["## 3. Sanity Check & Random Baseline"]))
cells.append(code([
    "import matplotlib.pyplot as plt\n",
    "\n",
    "env = UR5eGymEnv()\n",
    "obs, info = env.reset()\n",
    "print(f'Obs shape: {obs.shape}, range: [{obs.min():.2f}, {obs.max():.2f}], stage: {info[\"stage\"]}')\n",
    "\n",
    "rewards_random, success_random = [], 0\n",
    "for ep in range(100):\n",
    "    obs, _ = env.reset(); ep_r, done = 0, False\n",
    "    while not done:\n",
    "        obs, r, term, trunc, info = env.step(env.action_space.sample())\n",
    "        ep_r += r; done = term or trunc\n",
    "    rewards_random.append(ep_r)\n",
    "    if info['picked']: success_random += 1\n",
    "env.close()\n",
    "\n",
    "print(f'\\nRandom Policy: mean={np.mean(rewards_random):.2f}, std={np.std(rewards_random):.2f}, SR={success_random}%')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8,3), facecolor='#1e1e1e')\n",
    "ax.set_facecolor('#2d2d2d')\n",
    "ax.hist(rewards_random, bins=20, color='#00aaff', alpha=0.8)\n",
    "ax.axvline(np.mean(rewards_random), color='red', ls='--', label=f'Mean={np.mean(rewards_random):.1f}')\n",
    "ax.set_title('Random Policy Reward', color='white')\n",
    "ax.tick_params(colors='white'); ax.legend(facecolor='#333', labelcolor='white')\n",
    "plt.tight_layout(); plt.savefig(f'{BASE}/results/random_policy.png', dpi=120); plt.show()"
]))

# ====== CELL 4: Optuna ======
cells.append(md(["## 4. Hyperparameter Tuning (Optuna)"]))
cells.append(code([
    "import optuna, json\n",
    "from stable_baselines3 import SAC\n",
    "from stable_baselines3.common.vec_env import DummyVecEnv\n",
    "from stable_baselines3.common.evaluation import evaluate_policy\n",
    "\n",
    "def objective_sac(trial):\n",
    "    lr    = trial.suggest_float('lr', 1e-4, 1e-3, log=True)\n",
    "    bs    = trial.suggest_categorical('batch_size', [128, 256])\n",
    "    tau   = trial.suggest_float('tau', 0.001, 0.02)\n",
    "    gamma = trial.suggest_float('gamma', 0.95, 0.999)\n",
    "    try:\n",
    "        vec = DummyVecEnv([lambda: UR5eGymEnv()] * N_ENVS)\n",
    "        m = SAC('MlpPolicy', vec, learning_rate=lr, batch_size=bs,\n",
    "                tau=tau, gamma=gamma, buffer_size=100_000,\n",
    "                learning_starts=2000, verbose=0, device='cuda')\n",
    "        m.learn(total_timesteps=20_000)\n",
    "        ev = UR5eGymEnv()\n",
    "        mr, _ = evaluate_policy(m, ev, n_eval_episodes=10, deterministic=True)\n",
    "        ev.close(); vec.close()\n",
    "        return mr\n",
    "    except Exception as e:\n",
    "        print(f'Trial failed: {e}'); return -999.0\n",
    "\n",
    "study = optuna.create_study(direction='maximize')\n",
    "study.optimize(objective_sac, n_trials=15, show_progress_bar=True)\n",
    "BEST_PARAMS = study.best_params\n",
    "print(f'\\n\u2705 Best: {BEST_PARAMS} (value={study.best_value:.2f})')\n",
    "with open(f'{BASE}/models/optuna/best_params.json','w') as f:\n",
    "    json.dump(BEST_PARAMS, f, indent=2)\n",
    "fig = optuna.visualization.matplotlib.plot_optimization_history(study)\n",
    "plt.savefig(f'{BASE}/results/optuna_history.png', dpi=120); plt.show()"
]))

# ====== CELL 5: Train SAC ======
cells.append(md(["## 5. Train SAC (3 seeds)"]))
cells.append(code([
    "import json, time\n",
    "from stable_baselines3 import SAC\n",
    "from stable_baselines3.common.vec_env import SubprocVecEnv, DummyVecEnv, VecNormalize\n",
    "from stable_baselines3.common.callbacks import EvalCallback, CheckpointCallback, CallbackList, StopTrainingOnRewardThreshold\n",
    "from stable_baselines3.common.evaluation import evaluate_policy\n",
    "import torch.nn as nn\n",
    "\n",
    "with open(f'{BASE}/models/optuna/best_params.json') as f:\n",
    "    BEST = json.load(f)\n",
    "print(f'Params: {BEST}')\n",
    "\n",
    "TOTAL_SAC = 300_000\n",
    "sac_results = {}\n",
    "\n",
    "for seed in SEEDS:\n",
    "    print(f'\\n{\"=\"*50}\\n  SAC - Seed {seed}\\n{\"=\"*50}')\n",
    "    def make_env(): return UR5eGymEnv(gui=False, curriculum=True)\n",
    "    try: vec = SubprocVecEnv([make_env]*N_ENVS)\n",
    "    except: vec = DummyVecEnv([make_env]*N_ENVS)\n",
    "    vec = VecNormalize(vec, norm_obs=True, norm_reward=True, clip_obs=10.0, clip_reward=10.0)\n",
    "\n",
    "    eval_raw = UR5eGymEnv(gui=False)\n",
    "    eval_env = VecNormalize(DummyVecEnv([lambda: eval_raw]), norm_obs=True, norm_reward=False, clip_obs=10.0)\n",
    "\n",
    "    cbs = CallbackList([\n",
    "        CheckpointCallback(save_freq=25000, save_path=f'{BASE}/models/sac/seed{seed}',\n",
    "                           name_prefix=f'sac_s{seed}', verbose=1),\n",
    "        EvalCallback(eval_env, best_model_save_path=f'{BASE}/models/sac/best_s{seed}',\n",
    "                     log_path=f'{BASE}/logs/sac/seed{seed}', eval_freq=5000,\n",
    "                     n_eval_episodes=20, deterministic=True,\n",
    "                     callback_on_new_best=StopTrainingOnRewardThreshold(reward_threshold=40.0, verbose=1),\n",
    "                     verbose=1),\n",
    "    ])\n",
    "\n",
    "    model = SAC('MlpPolicy', vec,\n",
    "        learning_rate=BEST.get('lr',3e-4), buffer_size=200_000,\n",
    "        learning_starts=3000, batch_size=BEST.get('batch_size',256),\n",
    "        tau=BEST.get('tau',0.005), gamma=BEST.get('gamma',0.99),\n",
    "        train_freq=1, gradient_steps=1,\n",
    "        policy_kwargs=dict(net_arch=[256,256], activation_fn=nn.ReLU),\n",
    "        tensorboard_log=f'{BASE}/logs/tb', seed=seed, verbose=1, device='cuda')\n",
    "\n",
    "    t0 = time.time()\n",
    "    model.learn(total_timesteps=TOTAL_SAC, callback=cbs, progress_bar=True, tb_log_name=f'SAC_s{seed}')\n",
    "    elapsed = time.time()-t0\n",
    "\n",
    "    model.save(f'{BASE}/models/sac/sac_s{seed}_final')\n",
    "    vec.save(f'{BASE}/norm/sac_norm_s{seed}.pkl')\n",
    "    eval_env.obs_rms = vec.obs_rms\n",
    "    mr, sr = evaluate_policy(model, eval_env, n_eval_episodes=20, deterministic=True)\n",
    "    sac_results[str(seed)] = {'mean':float(mr),'std':float(sr),'time_h':elapsed/3600}\n",
    "    print(f'  Seed {seed}: {mr:.2f}+/-{sr:.2f} ({elapsed/3600:.1f}h)')\n",
    "    vec.close(); eval_env.close()\n",
    "\n",
    "with open(f'{BASE}/results/sac_results.json','w') as f:\n",
    "    json.dump(sac_results, f, indent=2)\n",
    "print('\\n\u2705 SAC all seeds done!')\n",
    "for s,r in sac_results.items(): print(f'  Seed {s}: {r[\"mean\"]:.2f}+/-{r[\"std\"]:.2f}')"
]))

# ====== CELL 6: Train PPO ======
cells.append(md(["## 6. Train PPO (3 seeds)"]))
cells.append(code([
    "from stable_baselines3 import PPO\n",
    "\n",
    "TOTAL_PPO = 500_000\n",
    "ppo_results = {}\n",
    "\n",
    "for seed in SEEDS:\n",
    "    print(f'\\n{\"=\"*50}\\n  PPO - Seed {seed}\\n{\"=\"*50}')\n",
    "    def make_env(): return UR5eGymEnv(gui=False, curriculum=True)\n",
    "    try: vec = SubprocVecEnv([make_env]*N_ENVS)\n",
    "    except: vec = DummyVecEnv([make_env]*N_ENVS)\n",
    "    vec = VecNormalize(vec, norm_obs=True, norm_reward=True, clip_obs=10.0, clip_reward=10.0)\n",
    "\n",
    "    eval_raw = UR5eGymEnv(gui=False)\n",
    "    eval_env = VecNormalize(DummyVecEnv([lambda: eval_raw]), norm_obs=True, norm_reward=False, clip_obs=10.0)\n",
    "\n",
    "    cbs = CallbackList([\n",
    "        CheckpointCallback(save_freq=25000, save_path=f'{BASE}/models/ppo/seed{seed}',\n",
    "                           name_prefix=f'ppo_s{seed}', verbose=1),\n",
    "        EvalCallback(eval_env, best_model_save_path=f'{BASE}/models/ppo/best_s{seed}',\n",
    "                     log_path=f'{BASE}/logs/ppo/seed{seed}', eval_freq=5000,\n",
    "                     n_eval_episodes=20, deterministic=True,\n",
    "                     callback_on_new_best=StopTrainingOnRewardThreshold(reward_threshold=40.0, verbose=1),\n",
    "                     verbose=1),\n",
    "    ])\n",
    "\n",
    "    model = PPO('MlpPolicy', vec,\n",
    "        learning_rate=BEST.get('lr',3e-4), n_steps=1024, batch_size=64,\n",
    "        n_epochs=10, gamma=BEST.get('gamma',0.99), gae_lambda=0.95,\n",
    "        clip_range=0.2, ent_coef=0.01, vf_coef=0.5, max_grad_norm=0.5,\n",
    "        policy_kwargs=dict(net_arch=dict(pi=[256,256],vf=[256,256]), activation_fn=nn.ReLU),\n",
    "        tensorboard_log=f'{BASE}/logs/tb', seed=seed, verbose=1, device='cuda')\n",
    "\n",
    "    t0 = time.time()\n",
    "    model.learn(total_timesteps=TOTAL_PPO, callback=cbs, progress_bar=True, tb_log_name=f'PPO_s{seed}')\n",
    "    elapsed = time.time()-t0\n",
    "\n",
    "    model.save(f'{BASE}/models/ppo/ppo_s{seed}_final')\n",
    "    vec.save(f'{BASE}/norm/ppo_norm_s{seed}.pkl')\n",
    "    eval_env.obs_rms = vec.obs_rms\n",
    "    mr, sr = evaluate_policy(model, eval_env, n_eval_episodes=20, deterministic=True)\n",
    "    ppo_results[str(seed)] = {'mean':float(mr),'std':float(sr),'time_h':elapsed/3600}\n",
    "    print(f'  Seed {seed}: {mr:.2f}+/-{sr:.2f} ({elapsed/3600:.1f}h)')\n",
    "    vec.close(); eval_env.close()\n",
    "\n",
    "with open(f'{BASE}/results/ppo_results.json','w') as f:\n",
    "    json.dump(ppo_results, f, indent=2)\n",
    "print('\\n\u2705 PPO all seeds done!')"
]))

# ====== CELL 7: Evaluation ======
cells.append(md(["## 7. Evaluation & Statistical Analysis"]))
cells.append(code([
    "from stable_baselines3 import SAC, PPO\n",
    "import json\n",
    "\n",
    "def calc_success_rate(model, norm_path, n=50):\n",
    "    raw = UR5eGymEnv(gui=False)\n",
    "    ev = VecNormalize.load(norm_path, DummyVecEnv([lambda: raw]))\n",
    "    ev.training = False; ev.norm_reward = False\n",
    "    ok = 0\n",
    "    for _ in range(n):\n",
    "        obs = ev.reset(); done = False\n",
    "        while not done:\n",
    "            a, _ = model.predict(obs, deterministic=True)\n",
    "            obs, _, done, info = ev.step(a)\n",
    "            if isinstance(done, np.ndarray): done = done[0]\n",
    "        if info[0].get('picked', False): ok += 1\n",
    "    ev.close()\n",
    "    return ok/n*100\n",
    "\n",
    "all_results = {}\n",
    "for algo, Cls in [('SAC',SAC),('PPO',PPO)]:\n",
    "    rews, srs = [], []\n",
    "    for seed in SEEDS:\n",
    "        m = Cls.load(f'{BASE}/models/{algo.lower()}/{algo.lower()}_s{seed}_final', device='cuda')\n",
    "        np_ = f'{BASE}/norm/{algo.lower()}_norm_s{seed}.pkl'\n",
    "        sr = calc_success_rate(m, np_, n=50); srs.append(sr)\n",
    "        raw = UR5eGymEnv(gui=False)\n",
    "        ev = VecNormalize.load(np_, DummyVecEnv([lambda: raw]))\n",
    "        ev.training = ev.norm_reward = False\n",
    "        mr, _ = evaluate_policy(m, ev, n_eval_episodes=50, deterministic=True)\n",
    "        rews.append(float(mr)); ev.close()\n",
    "    all_results[algo] = {'rewards':rews,'success_rates':srs,\n",
    "        'mean_reward':float(np.mean(rews)),'std_reward':float(np.std(rews)),\n",
    "        'mean_sr':float(np.mean(srs)),'std_sr':float(np.std(srs))}\n",
    "\n",
    "print(f'\\n{\"=\"*55}\\n  RESULTS (mean +/- std, 3 seeds)\\n{\"=\"*55}')\n",
    "for algo, r in all_results.items():\n",
    "    print(f'  {algo}: Reward={r[\"mean_reward\"]:.2f}+/-{r[\"std_reward\"]:.2f}  SR={r[\"mean_sr\"]:.1f}%+/-{r[\"std_sr\"]:.1f}%')\n",
    "winner = max(all_results, key=lambda k: all_results[k]['mean_sr'])\n",
    "print(f'\\n  \ud83c\udfc6 Winner: {winner}')\n",
    "with open(f'{BASE}/results/final_results.json','w') as f:\n",
    "    json.dump(all_results, f, indent=2)"
]))

# ====== CELL 8: Plots ======
cells.append(md(["## 8. Learning Curves & Plots"]))
cells.append(code([
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "\n",
    "COLORS = {'SAC':'#00aaff','PPO':'#ff8800'}\n",
    "fig, axes = plt.subplots(2,3,figsize=(18,10))\n",
    "fig.patch.set_facecolor('#1e1e1e')\n",
    "for ax in axes.flat:\n",
    "    ax.set_facecolor('#2d2d2d'); ax.tick_params(colors='white')\n",
    "    ax.xaxis.label.set_color('white'); ax.yaxis.label.set_color('white')\n",
    "    ax.title.set_color('white')\n",
    "    for sp in ax.spines.values(): sp.set_edgecolor('#555')\n",
    "\n",
    "# Plot 1: Mean Reward\n",
    "ax = axes[0,0]\n",
    "for algo, color in COLORS.items():\n",
    "    all_r, ts = [], None\n",
    "    for seed in SEEDS:\n",
    "        d = np.load(f'{BASE}/logs/{algo.lower()}/seed{seed}/evaluations.npz')\n",
    "        if ts is None: ts = d['timesteps']\n",
    "        all_r.append(d['results'].mean(1))\n",
    "    all_r = np.array(all_r); m,s = all_r.mean(0), all_r.std(0)\n",
    "    ax.plot(ts, m, color=color, lw=2, label=algo)\n",
    "    ax.fill_between(ts, m-s, m+s, alpha=0.2, color=color)\n",
    "ax.set_title('Mean Reward (3 seeds)'); ax.set_xlabel('Steps'); ax.set_ylabel('Reward')\n",
    "ax.legend(facecolor='#333', labelcolor='white'); ax.grid(True, alpha=0.3)\n",
    "\n",
    "# Plot 2: Success Rate\n",
    "ax = axes[0,1]\n",
    "for algo, color in COLORS.items():\n",
    "    all_sr = []\n",
    "    for seed in SEEDS:\n",
    "        d = np.load(f'{BASE}/logs/{algo.lower()}/seed{seed}/evaluations.npz')\n",
    "        all_sr.append((d['results']>30).mean(1)*100)\n",
    "    all_sr = np.array(all_sr); m,s = all_sr.mean(0), all_sr.std(0)\n",
    "    ax.plot(d['timesteps'], m, color=color, lw=2, label=algo)\n",
    "    ax.fill_between(d['timesteps'], m-s, m+s, alpha=0.2, color=color)\n",
    "ax.set_title('Success Rate'); ax.set_xlabel('Steps'); ax.set_ylabel('%'); ax.set_ylim(0,105)\n",
    "ax.legend(facecolor='#333', labelcolor='white'); ax.grid(True, alpha=0.3)\n",
    "\n",
    "# Plot 3: Episode Length\n",
    "ax = axes[0,2]\n",
    "for algo, color in COLORS.items():\n",
    "    all_ep = []\n",
    "    for seed in SEEDS:\n",
    "        d = np.load(f'{BASE}/logs/{algo.lower()}/seed{seed}/evaluations.npz')\n",
    "        all_ep.append(d['ep_lengths'].mean(1))\n",
    "    all_ep = np.array(all_ep); m,s = all_ep.mean(0), all_ep.std(0)\n",
    "    ax.plot(d['timesteps'], m, color=color, lw=2, label=algo)\n",
    "    ax.fill_between(d['timesteps'], m-s, m+s, alpha=0.2, color=color)\n",
    "ax.set_title('Episode Length'); ax.set_xlabel('Steps'); ax.set_ylabel('Steps')\n",
    "ax.legend(facecolor='#333', labelcolor='white'); ax.grid(True, alpha=0.3)\n",
    "\n",
    "# Plot 4: SR Bar per seed\n",
    "ax = axes[1,0]; x = np.arange(len(SEEDS)); w = 0.35\n",
    "for i,(algo,color) in enumerate(COLORS.items()):\n",
    "    sr = all_results[algo]['success_rates']\n",
    "    bars = ax.bar(x+i*w, sr, w, color=color, alpha=0.8, label=algo)\n",
    "    for bar,v in zip(bars,sr): ax.text(bar.get_x()+bar.get_width()/2, v+1, f'{v:.0f}%', ha='center', color='white', fontsize=9)\n",
    "ax.set_title('SR per Seed'); ax.set_xticks(x+w/2); ax.set_xticklabels([f'Seed {s}' for s in SEEDS])\n",
    "ax.set_ylim(0,110); ax.legend(facecolor='#333',labelcolor='white'); ax.grid(True,alpha=0.3,axis='y')\n",
    "\n",
    "# Plot 5: Final bar\n",
    "ax = axes[1,1]; algos = list(COLORS.keys())\n",
    "means = [all_results[a]['mean_sr'] for a in algos]\n",
    "stds  = [all_results[a]['std_sr']  for a in algos]\n",
    "colors_= [COLORS[a] for a in algos]\n",
    "bars = ax.bar(algos, means, yerr=stds, color=colors_, alpha=0.85, capsize=8, width=0.5)\n",
    "for bar,m,s in zip(bars,means,stds): ax.text(bar.get_x()+bar.get_width()/2, m+s+1.5, f'{m:.1f}+/-{s:.1f}%', ha='center', color='white', fontweight='bold')\n",
    "ax.set_title('Final SR (mean+/-std)'); ax.set_ylim(0,110); ax.grid(True,alpha=0.3,axis='y')\n",
    "\n",
    "# Plot 6: Summary table\n",
    "ax = axes[1,2]; ax.axis('off')\n",
    "td = [[a, f'{all_results[a][\"mean_reward\"]:.1f}', f'{all_results[a][\"mean_sr\"]:.1f}%', '\u2705' if a==winner else ''] for a in algos]\n",
    "t = ax.table(cellText=td, colLabels=['Algo','Reward','SR','Win'], cellLoc='center', loc='center')\n",
    "t.auto_set_font_size(False); t.set_fontsize(11); t.scale(1.2,2.0)\n",
    "for (r,c),cell in t.get_celld().items():\n",
    "    cell.set_facecolor('#2d2d2d' if r>0 else '#444'); cell.set_text_props(color='white'); cell.set_edgecolor('#555')\n",
    "\n",
    "plt.suptitle('SAC vs PPO - UR5e Pick & Place (Colab T4)', fontsize=14, fontweight='bold', color='white', y=1.01)\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{BASE}/results/final_comparison.png', dpi=150, bbox_inches='tight', facecolor='#1e1e1e')\n",
    "plt.show()\n",
    "print(f'\u2705 Saved: {BASE}/results/final_comparison.png')"
]))

# ====== CELL 9: Video ======
cells.append(md(["## 9. Video Demo"]))
cells.append(code([
    "import imageio\n",
    "\n",
    "# Virtual display for Colab\n",
    "!apt-get install -y xvfb > /dev/null 2>&1\n",
    "!pip install -q pyvirtualdisplay\n",
    "from pyvirtualdisplay import Display\n",
    "display = Display(visible=0, size=(1024,768)); display.start()\n",
    "\n",
    "def record_episode(model, norm_path, video_path, fps=30):\n",
    "    raw = UR5eGymEnv(gui=True)\n",
    "    env = VecNormalize.load(norm_path, DummyVecEnv([lambda: raw]))\n",
    "    env.training = env.norm_reward = False\n",
    "    frames, obs, done, step = [], env.reset(), False, 0\n",
    "    while not done and step < 200:\n",
    "        a, _ = model.predict(obs, deterministic=True)\n",
    "        obs, _, done, info = env.step(a)\n",
    "        if isinstance(done, np.ndarray): done = done[0]\n",
    "        frame = p.getCameraImage(640, 480,\n",
    "            viewMatrix=p.computeViewMatrixFromYawPitchRoll([0.5,0,0.3], 1.2, 45, -35, 0, 2),\n",
    "            projectionMatrix=p.computeProjectionMatrixFOV(60, 640/480, 0.1, 3.0))[2]\n",
    "        frames.append(frame[:,:,:3]); step += 1\n",
    "    env.close()\n",
    "    imageio.mimsave(video_path, frames, fps=fps)\n",
    "    print(f'\u2705 Video: {video_path}')\n",
    "\n",
    "# Record best SAC\n",
    "best_s = SEEDS[np.argmax(all_results['SAC']['success_rates'])]\n",
    "sac_m = SAC.load(f'{BASE}/models/sac/sac_s{best_s}_final', device='cuda')\n",
    "record_episode(sac_m, f'{BASE}/norm/sac_norm_s{best_s}.pkl', f'{BASE}/videos/sac_demo.mp4')\n",
    "\n",
    "# Record best PPO\n",
    "best_p = SEEDS[np.argmax(all_results['PPO']['success_rates'])]\n",
    "ppo_m = PPO.load(f'{BASE}/models/ppo/ppo_s{best_p}_final', device='cuda')\n",
    "record_episode(ppo_m, f'{BASE}/norm/ppo_norm_s{best_p}.pkl', f'{BASE}/videos/ppo_demo.mp4')\n",
    "\n",
    "display.stop()"
]))

# ====== CELL 10: Resume ======
cells.append(md(["## 10. Resume Training (n\u1ebfu disconnect)"]))
cells.append(code([
    "import glob\n",
    "\n",
    "def resume(ModelClass, algo, seed, total_steps, steps_done):\n",
    "    ckpt_dir  = f'{BASE}/models/{algo}/seed{seed}'\n",
    "    norm_path = f'{BASE}/norm/{algo}_norm_s{seed}.pkl'\n",
    "    ckpts = sorted(glob.glob(f'{ckpt_dir}/*.zip'))\n",
    "    if not ckpts:\n",
    "        print(f'\u274c No checkpoint for {algo} seed{seed}'); return\n",
    "    latest = ckpts[-1]\n",
    "    print(f'\ud83d\udcc2 Loading: {os.path.basename(latest)}')\n",
    "\n",
    "    def make_env(): return UR5eGymEnv(gui=False, curriculum=True)\n",
    "    try: vec = SubprocVecEnv([make_env]*N_ENVS)\n",
    "    except: vec = DummyVecEnv([make_env]*N_ENVS)\n",
    "\n",
    "    if os.path.exists(norm_path):\n",
    "        vec = VecNormalize.load(norm_path, vec); vec.training = True\n",
    "    else:\n",
    "        vec = VecNormalize(vec)\n",
    "\n",
    "    model = ModelClass.load(latest, env=vec, device='cuda')\n",
    "    remaining = total_steps - steps_done\n",
    "    print(f'\u23e9 Remaining: {remaining:,} steps')\n",
    "    model.learn(total_timesteps=remaining, reset_num_timesteps=False,\n",
    "                progress_bar=True, tb_log_name=f'{algo.upper()}_s{seed}_resume')\n",
    "    model.save(f'{BASE}/models/{algo}/{algo}_s{seed}_final')\n",
    "    vec.save(norm_path); vec.close()\n",
    "    print('\u2705 Resume complete!')\n",
    "\n",
    "# === UNCOMMENT de resume ===\n",
    "# resume(SAC, 'sac', seed=42, total_steps=300_000, steps_done=100_000)\n",
    "# resume(PPO, 'ppo', seed=123, total_steps=500_000, steps_done=200_000)\n",
    "print('Resume cell ready. Uncomment dong can resume va chay!')"
]))

# ====== Build notebook ======
nb = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU"
    },
    "cells": cells
}

out_path = "UR5e_SAC_vs_PPO.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook saved: {out_path}")
print(f"Total cells: {len(cells)}")
